# Generated by Django 3.2.15 on 2022-09-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_wants',
            field=models.CharField(choices=[('learning', 'Learning'), ('teaching', 'Teaching'), ('developing', 'Developing')], default='learning', max_length=20),
        ),
    ]
