# Generated by Django 3.2.15 on 2022-10-03 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
        ('users', '0005_profile_user_wants'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.badges'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.interests'),
        ),
        migrations.AddField(
            model_name='profile',
            name='to_learn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attributes.tolerncategories'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
